version: '2'
services:
  web:
    build: .
    ports: 
     - 8080:8080
     - 9990:9990
    environment:
     - JBOSS_PASS=jboss
     - HOSTNAMELINK=db
     - DBNAME=GOG
     - DBUSERNAME=gog
     - DBPASSWORD=gog 
     - DBSCHEMA=ouvidoria
    depends_on:
      - db
  db:
    build:
      context: ./postgresql_9.3
    ports: 
     - 5432:5432
    environment:
     - POSTGRES_DB=GOG
     - POSTGRES_USER=gog
     - POSTGRES_PASSWORD=gog
